[tox]
envlist =
    py310
    py311
    py312
    py313
    mypy
    muff-lint
    muff-format
    pre-commit

testenv_list = {envlist}

[testenv]
package = wheel
wheel_build_env = .pkg
deps =
    pytest
commands =
    pytest --tb=long

[testenv:mypy]
deps =
    mypy
commands =
    mypy click_config_file_injection_utils

[testenv:muff-lint]
deps =
    muff
skip_install = true
commands =
    muff check --fix --config=muff.toml click_config_file_injection_utils tests

[testenv:muff-format]
deps =
    muff
skip_install = true
commands =
    muff format --diff --config=muff.toml click_config_file_injection_utils tests

[testenv:pre-commit]
skip_install = true
deps =
    pre-commit
set_env =
    SKIP = muff
commands =
    pre-commit run -a
